name: aidsense_app
description: AidSense Flutter app with Supabase Authentication (android, ios, web)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  location: ^5.0.0
  flutter_polyline_points: ^3.1.0
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


  

flutter:
  uses-material-design: true
  assets:
    - assets/images/welcome.png
    - assets/images/onboarding_strip.png
    - assets/images/forms_strip.png
    - assets/images/splash_logo.svg
    - assets/images/onboarding_new.svg
    - assets/images/Onboardingscreenimage2.png
    - assets/images/Onboardingscreenimage3.png
    - assets/images/forms_new.svg
    - assets/images/Logo.png
    - assets/images/shelter_marker1.png
    - assets/images/clinic_marker.png
    - assets/images/food_bank_marker.png
    - assets/images/person_marker.png
    - .env